# This is a basic workflow to help you get started with Actions

name: My Simple Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        name: checkout using sha for v3

      - uses: actions/checkout@v2
        name: Checkout using tag v2

      
